# Generated by Django 4.2.6 on 2023-11-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_books_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pictures',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
