# Generated by Django 4.2.6 on 2023-11-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_books_pictures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='pictures',
            new_name='picture',
        ),
    ]
